Ext.namespace("Usuario");
var co_usuario;
var tx_usuario;
var co_supervisor;
var tx_supervisor;
/*function verificarUsuario() {
	Ext.Ajax.request({
		url: 'php/UsuariosInterfaz.php',
		params: { 
			tx_usuario: Ext.getCmp('tx_usuario').getValue(), 
			tx_password: Ext.getCmp('tx_password').getValue(),
			co_rol: Ext.getCmp("co_rol").getValue(),
			tx_rol: Ext.getCmp("co_rol").getRawValue(),
			//filter:'',
			accion:'login'
		},*/
		success: function (response, option){
			obj = Ext.util.JSON.decode(response.responseText);
			
			if(obj.resp){
				co_usuario=obj.Resultados[0].co_usuario;
				tx_usuario=obj.Resultados[0].tx_usuario;
				co_supervisor=obj.Resultados[0].co_supervisor;
				tx_supervisor=obj.Resultados[0].tx_supervisor;
				Ext.getCmp("statusbarFecha").setText(obj.Resultados[0].fecha);
				Ext.getCmp("statusbarIndicador").setText(tx_usuario);
				Ext.getCmp("statusbarRol").setText(obj.Resultados[0].tx_rol);
				Ext.getCmp("super_plani").store.reload();
				//console.log(obj.Resultados[0].tx_usuario);
				
				switch (Ext.getCmp("co_rol").getValue()/*obj.Resultados[0].co_rol*/){
					
					case '0'://Administrador del Sistema
						Ext.getCmp('menu_planificacion').enable();
						Ext.getCmp('menu_contratacion').enable();
						Ext.getCmp('menu_administracion_contratos').enable();
						//Ext.getCmp('menu_usuarios').enable();
						Ext.getCmp('menu_graficas').enable();
						Ext.getCmp('menu_usuarios').enable();
						Ext.getCmp('menu_administracion').enable();
						store_planificacion.load();
						store_usuarios.load();
					break;
			
					case '1'://Gerente de Area
						Ext.getCmp('menu_planificacion').enable();
						Ext.getCmp('menu_contratacion').enable();
						Ext.getCmp('menu_administracion_contratos').disable(); //luego desbloquear
						Ext.getCmp('menu_graficas').enable();
						Ext.getCmp('menu_usuarios').disable();
						Ext.getCmp('menu_administracion').disable();
						//planificacion
						Ext.getCmp('boton-guardar-planificacion').disable();
						Ext.getCmp('boton-guardar-planificacion2').disable();
						Ext.getCmp('boton_guardar_solicitud').disable();
						Ext.getCmp('boton-cerrar-planificacion').disable();
						Ext.getCmp('boton_cerrar_procesos').disable();
						Ext.getCmp('boton_cancelar_solicitud').disable();
						Ext.getCmp('boton-nuevo-proceso').disable();
						Ext.getCmp('boton-eliminar-proceso').disable();
						Ext.getCmp('boton-exportar-excel-proceso').disable();
						Ext.getCmp('boton-imprimir-proceso').disable();
						//contratacion
						Ext.getCmp('boton_exportar_excel_contratacion').disable();
						Ext.getCmp('boton_guardar_datos_generales').disable();
						Ext.getCmp('boton_guardar_datos_procesos').disable();
						Ext.getCmp('boton_guardar_empresa').disable();
						Ext.getCmp('boton_guardar_unidades').disable();
						Ext.getCmp('boton_guardar_panel_cronograma').disable();
						Ext.getCmp('boton_guardar_resultados_rif').disable();
						Ext.getCmp('boton_cerrar_datos_generales').disable();
						Ext.getCmp('boton_cerrar_datos_procesos').disable();
						Ext.getCmp('boton_cerrar_panel_cronograma').disable();
						Ext.getCmp('boton_nuevo_unidades').disable();
						Ext.getCmp('boton_nuevo_resultado_rif').disable();
						Ext.getCmp('boton_eliminar_unidades').disable();
						Ext.getCmp('boton_eliminar_resultados_rif').disable();
						Ext.getCmp('boton_nueva_rif').disable();
						//administracion
						Ext.getCmp('boton_nuevo_contrato').disable();
						Ext.getCmp('boton_nuevo_tramites').disable();
						Ext.getCmp('boton_nuevo_pedido').disable();
						Ext.getCmp('boton_nuevo_Aporte').disable();
						Ext.getCmp('boton_nuevo_condiciones').disable();
						Ext.getCmp('boton_nuevo_Anticipo').disable();
						Ext.getCmp('boton_nuevo_valuacion').disable();
						Ext.getCmp('boton_nueva_modificacion').disable();
						Ext.getCmp('boton_nuevo_Cierre').disable();
						Ext.getCmp('boton_guardar_pedido').disable();
						Ext.getCmp('boton_guardar_asignar').disable();
						Ext.getCmp('boton_guardar_tabpanel_DatosFom').disable();
						Ext.getCmp('boton_guardar_Aporte').disable();
						Ext.getCmp('boton_guardar_condiciones').disable();
						Ext.getCmp('boton_guardar_Anticipo').disable();
						Ext.getCmp('boton_guardar_modificar').disable();
						Ext.getCmp('boton_guardar_fianzas').disable();
						Ext.getCmp('boton_guardar_paralizaciones').disable();
						Ext.getCmp('boton_guardar_variaciones').disable();
						Ext.getCmp('boton_guardar_valuacion').disable();
						Ext.getCmp('boton_guardar_tramite').disable();
						Ext.getCmp('boton_guardar_cierre').disable();
						Ext.getCmp('boton_eliminar_nuevo_pedido').disable();
						Ext.getCmp('boton_eliminar_nuevo_Aporte').disable();
						Ext.getCmp('boton_eliminar_nuevo_condiciones').disable();
						Ext.getCmp('boton_eliminar_nuevo_Anticipo').disable();
						Ext.getCmp('boton_eliminar_nuevo_valuacion').disable();
						Ext.getCmp('boton_eliminar_nuevo_cierre').disable();
						Ext.getCmp('boton_eliminar_contrato').disable();
						Ext.getCmp('boton_eliminar_tramite').disable();
						Ext.getCmp('usuario').disable();
						//Ext.getCmp('boton_cerrar_tabpanel').enable();
						/*Ext.getCmp('').disable();
						Ext.getCmp('').disable();*/
						store_planificacion.load();
					break;
			
					case '2'://Lider de Planificacion
						Ext.getCmp('menu_planificacion').enable();
						Ext.getCmp('menu_contratacion').enable();//para que el usuario no pueda ver
						Ext.getCmp('menu_administracion_contratos').disable();
						//Ext.getCmp('menu_usuarios').disable();
						Ext.getCmp('usuario_analista').enable();
						Ext.getCmp('menu_graficas').enable();
						Ext.getCmp('menu_usuarios').disable();
						Ext.getCmp('menu_administracion').disable();
						//planificacion
						Ext.getCmp('boton-guardar-planificacion').enable();
						Ext.getCmp('boton-guardar-planificacion2').enable();
						Ext.getCmp('boton_guardar_solicitud').enable();
						Ext.getCmp('boton-cerrar-planificacion').enable();
						Ext.getCmp('boton_cerrar_procesos').enable();
						Ext.getCmp('boton_cancelar_solicitud').enable();
						Ext.getCmp('boton-nuevo-proceso').enable();
						Ext.getCmp('boton-eliminar-proceso').enable();
						Ext.getCmp('boton-exportar-excel-proceso').enable();
						Ext.getCmp('boton-imprimir-proceso').enable();
						//contratacion
						Ext.getCmp('boton_exportar_excel_contratacion').disable();
						Ext.getCmp('boton_guardar_datos_generales').disable();
						Ext.getCmp('boton_guardar_datos_procesos').disable();
						Ext.getCmp('boton_guardar_empresa').disable();
						Ext.getCmp('boton_guardar_unidades').disable();
						Ext.getCmp('boton_guardar_panel_cronograma').disable();
						Ext.getCmp('boton_guardar_resultados_rif').disable();
						Ext.getCmp('boton_cerrar_datos_generales').disable();
						Ext.getCmp('boton_cerrar_datos_procesos').disable();
						Ext.getCmp('boton_cerrar_panel_cronograma').disable();
						Ext.getCmp('boton_nuevo_unidades').disable();
						Ext.getCmp('boton_nuevo_resultado_rif').disable();
						Ext.getCmp('boton_eliminar_unidades').disable();
						Ext.getCmp('boton_eliminar_resultados_rif').disable();
						Ext.getCmp('boton_nueva_rif').disable();
						//administracion
						Ext.getCmp('boton_nuevo_contrato').disable();
						Ext.getCmp('boton_nuevo_tramites').disable();
						Ext.getCmp('boton_nuevo_pedido').disable();
						Ext.getCmp('boton_nuevo_Aporte').disable();
						Ext.getCmp('boton_nuevo_condiciones').disable();
						Ext.getCmp('boton_nuevo_Anticipo').disable();
						Ext.getCmp('boton_nuevo_valuacion').disable();
						Ext.getCmp('boton_nueva_modificacion').disable();
						Ext.getCmp('boton_nuevo_Cierre').disable();
						Ext.getCmp('boton_guardar_pedido').disable();
						Ext.getCmp('boton_guardar_asignar').disable();
						Ext.getCmp('boton_guardar_tabpanel_DatosFom').disable();
						Ext.getCmp('boton_guardar_Aporte').disable();
						Ext.getCmp('boton_guardar_condiciones').disable();
						Ext.getCmp('boton_guardar_Anticipo').disable();
						Ext.getCmp('boton_guardar_modificar').disable();
						Ext.getCmp('boton_guardar_fianzas').disable();
						Ext.getCmp('boton_guardar_paralizaciones').disable();
						Ext.getCmp('boton_guardar_variaciones').disable();
						Ext.getCmp('boton_guardar_valuacion').disable();
						Ext.getCmp('boton_guardar_tramite').disable();
						Ext.getCmp('boton_guardar_cierre').disable();
						Ext.getCmp('boton_eliminar_nuevo_pedido').disable();
						Ext.getCmp('boton_eliminar_nuevo_Aporte').disable();
						Ext.getCmp('boton_eliminar_nuevo_condiciones').disable();
						Ext.getCmp('boton_eliminar_nuevo_Anticipo').disable();
						Ext.getCmp('boton_eliminar_nuevo_valuacion').disable();
						Ext.getCmp('boton_eliminar_nuevo_cierre').disable();
						Ext.getCmp('boton_eliminar_contrato').disable();
						Ext.getCmp('boton_eliminar_tramite').disable();
						Ext.getCmp('usuario').disable();
						//Ext.getCmp('boton_cerrar_tabpanel').enable();
						store_planificacion.load();
					break;
			
					case '3'://Supervisor de Planificacion
						Ext.getCmp('menu_planificacion').enable();
						Ext.getCmp('menu_contratacion').enable();
						Ext.getCmp('menu_administracion_contratos').disable();
						//Ext.getCmp('menu_usuarios').disable();
						Ext.getCmp('menu_graficas').enable();
						Ext.getCmp('menu_usuarios').disable();
						Ext.getCmp('menu_administracion').disable();
						//planificacion
						Ext.getCmp('boton-guardar-planificacion').enable();
						Ext.getCmp('boton-guardar-planificacion2').enable();
						Ext.getCmp('boton_guardar_solicitud').enable();
						Ext.getCmp('boton-cerrar-planificacion').enable();
						Ext.getCmp('boton_cerrar_procesos').enable();
						Ext.getCmp('boton_cancelar_solicitud').enable();
						Ext.getCmp('boton-nuevo-proceso').enable();
						Ext.getCmp('boton-eliminar-proceso').enable();
						Ext.getCmp('boton-exportar-excel-proceso').enable();
						Ext.getCmp('boton-imprimir-proceso').enable();
						//contratacion
						Ext.getCmp('boton_exportar_excel_contratacion').disable();
						Ext.getCmp('boton_guardar_datos_generales').disable();
						Ext.getCmp('boton_guardar_datos_procesos').disable();
						Ext.getCmp('boton_guardar_empresa').disable();
						Ext.getCmp('boton_guardar_unidades').disable();
						Ext.getCmp('boton_guardar_panel_cronograma').disable();
						Ext.getCmp('boton_guardar_resultados_rif').disable();
						Ext.getCmp('boton_cerrar_datos_generales').disable();
						Ext.getCmp('boton_cerrar_datos_procesos').disable();
						Ext.getCmp('boton_cerrar_panel_cronograma').disable();
						Ext.getCmp('boton_nuevo_unidades').disable();
						Ext.getCmp('boton_nuevo_resultado_rif').disable();
						Ext.getCmp('boton_eliminar_unidades').disable();
						Ext.getCmp('boton_eliminar_resultados_rif').disable();
						Ext.getCmp('boton_nueva_rif').disable();
						//administracion
						Ext.getCmp('boton_nuevo_contrato').disable();
						Ext.getCmp('boton_nuevo_tramites').disable();
						Ext.getCmp('boton_nuevo_pedido').disable();
						Ext.getCmp('boton_nuevo_Aporte').disable();
						Ext.getCmp('boton_nuevo_condiciones').disable();
						Ext.getCmp('boton_nuevo_Anticipo').disable();
						Ext.getCmp('boton_nuevo_valuacion').disable();
						Ext.getCmp('boton_nueva_modificacion').disable();
						Ext.getCmp('boton_nuevo_Cierre').disable();
						Ext.getCmp('boton_guardar_pedido').disable();
						Ext.getCmp('boton_guardar_asignar').disable();
						Ext.getCmp('boton_guardar_tabpanel_DatosFom').disable();
						Ext.getCmp('boton_guardar_Aporte').disable();
						Ext.getCmp('boton_guardar_condiciones').disable();
						Ext.getCmp('boton_guardar_Anticipo').disable();
						Ext.getCmp('boton_guardar_modificar').disable();
						Ext.getCmp('boton_guardar_fianzas').disable();
						Ext.getCmp('boton_guardar_paralizaciones').disable();
						Ext.getCmp('boton_guardar_variaciones').disable();
						Ext.getCmp('boton_guardar_valuacion').disable();
						Ext.getCmp('boton_guardar_tramite').disable();
						Ext.getCmp('boton_guardar_cierre').disable();
						Ext.getCmp('boton_eliminar_nuevo_pedido').disable();
						Ext.getCmp('boton_eliminar_nuevo_Aporte').disable();
						Ext.getCmp('boton_eliminar_nuevo_condiciones').disable();
						Ext.getCmp('boton_eliminar_nuevo_Anticipo').disable();
						Ext.getCmp('boton_eliminar_nuevo_valuacion').disable();
						Ext.getCmp('boton_eliminar_nuevo_cierre').disable();
						Ext.getCmp('boton_eliminar_contrato').disable();
						Ext.getCmp('boton_eliminar_tramite').disable();
						Ext.getCmp('usuario').disable();
						//Ext.getCmp('boton_cerrar_tabpanel').enable();
						store_planificacion.load();
					break;
					
						case '4'://Lider de Contratacion
						Ext.getCmp('menu_planificacion').disable();
						Ext.getCmp('menu_contratacion').enable();
						Ext.getCmp('menu_administracion_contratos').disable();
						//Ext.getCmp('menu_usuarios').disable();
						Ext.getCmp('menu_graficas').enable();
						Ext.getCmp('menu_usuarios').disable();
						Ext.getCmp('menu_administracion').disable();
						//contratacion
						Ext.getCmp('boton_exportar_excel_contratacion').enable();
						Ext.getCmp('boton_guardar_datos_generales').enable();
						Ext.getCmp('boton_guardar_datos_procesos').disable();
						Ext.getCmp('boton_guardar_empresa').disable();
						Ext.getCmp('boton_guardar_unidades').disable();
						Ext.getCmp('boton_guardar_panel_cronograma').disable();
						Ext.getCmp('boton_guardar_resultados_rif').disable();
						Ext.getCmp('boton_cerrar_datos_generales').disable();
						Ext.getCmp('boton_cerrar_datos_procesos').disable();
						Ext.getCmp('boton_cerrar_panel_cronograma').disable();
						Ext.getCmp('boton_nuevo_unidades').disable();
						Ext.getCmp('boton_nuevo_resultado_rif').disable();
						Ext.getCmp('boton_eliminar_unidades').disable();
						Ext.getCmp('boton_eliminar_resultados_rif').disable();
						Ext.getCmp('boton_nueva_rif').disable();
						//administracion
						Ext.getCmp('boton_nuevo_contrato').disable();
						Ext.getCmp('boton_nuevo_tramites').disable();
						Ext.getCmp('boton_nuevo_pedido').disable();
						Ext.getCmp('boton_nuevo_Aporte').disable();
						Ext.getCmp('boton_nuevo_condiciones').disable();
						Ext.getCmp('boton_nuevo_Anticipo').disable();
						Ext.getCmp('boton_nuevo_valuacion').disable();
						Ext.getCmp('boton_nueva_modificacion').disable();
						Ext.getCmp('boton_nuevo_Cierre').disable();
						Ext.getCmp('boton_guardar_pedido').disable();
						Ext.getCmp('boton_guardar_asignar').disable();
						Ext.getCmp('boton_guardar_tabpanel_DatosFom').disable();
						Ext.getCmp('boton_guardar_Aporte').disable();
						Ext.getCmp('boton_guardar_condiciones').disable();
						Ext.getCmp('boton_guardar_Anticipo').disable();
						Ext.getCmp('boton_guardar_modificar').disable();
						Ext.getCmp('boton_guardar_fianzas').disable();
						Ext.getCmp('boton_guardar_paralizaciones').disable();
						Ext.getCmp('boton_guardar_variaciones').disable();
						Ext.getCmp('boton_guardar_valuacion').disable();
						Ext.getCmp('boton_guardar_tramite').disable();
						Ext.getCmp('boton_guardar_cierre').disable();
						Ext.getCmp('boton_eliminar_nuevo_pedido').disable();
						Ext.getCmp('boton_eliminar_nuevo_Aporte').disable();
						Ext.getCmp('boton_eliminar_nuevo_condiciones').disable();
						Ext.getCmp('boton_eliminar_nuevo_Anticipo').disable();
						Ext.getCmp('boton_eliminar_nuevo_valuacion').disable();
						Ext.getCmp('boton_eliminar_nuevo_cierre').disable();
						Ext.getCmp('boton_eliminar_contrato').disable();
						Ext.getCmp('boton_eliminar_tramite').disable();
						Ext.getCmp('usuario').disable();
						//Ext.getCmp('boton_cerrar_tabpanel').enable();
						store_planificacion.load();
					break;
					case '5'://Supervisor de Contratacion
						Ext.getCmp('menu_planificacion').disable();;
						Ext.getCmp('menu_contratacion').enable();
						Ext.getCmp('menu_administracion_contratos').disable();
						//Ext.getCmp('menu_usuarios').disable();
						Ext.getCmp('menu_graficas').enable();
						Ext.getCmp('menu_usuarios').disable();
						Ext.getCmp('menu_administracion').disable();
						//contratacion
						Ext.getCmp('usuario_supervisor').disable();
						Ext.getCmp('boton_exportar_excel_contratacion').enable();
						Ext.getCmp('boton_guardar_datos_generales').enable();
						Ext.getCmp('boton_guardar_datos_procesos').disable();
						Ext.getCmp('boton_guardar_empresa').disable();
						Ext.getCmp('boton_guardar_unidades').disable();
						Ext.getCmp('boton_guardar_panel_cronograma').disable();
						Ext.getCmp('boton_guardar_resultados_rif').disable();
						Ext.getCmp('boton_cerrar_datos_generales').disable();
						Ext.getCmp('boton_cerrar_datos_procesos').disable();
						Ext.getCmp('boton_cerrar_panel_cronograma').disable();
						Ext.getCmp('boton_nuevo_unidades').disable();
						Ext.getCmp('boton_nuevo_resultado_rif').disable();
						Ext.getCmp('boton_eliminar_unidades').disable();
						Ext.getCmp('boton_eliminar_resultados_rif').disable();
						Ext.getCmp('boton_nueva_rif').disable();
						//administracion
						Ext.getCmp('boton_nuevo_contrato').disable();
						Ext.getCmp('boton_nuevo_tramites').disable();
						Ext.getCmp('boton_nuevo_pedido').disable();
						Ext.getCmp('boton_nuevo_Aporte').disable();
						Ext.getCmp('boton_nuevo_condiciones').disable();
						Ext.getCmp('boton_nuevo_Anticipo').disable();
						Ext.getCmp('boton_nuevo_valuacion').disable();
						Ext.getCmp('boton_nueva_modificacion').disable();
						Ext.getCmp('boton_nuevo_Cierre').disable();
						Ext.getCmp('boton_guardar_pedido').disable();
						Ext.getCmp('boton_guardar_asignar').disable();
						Ext.getCmp('boton_guardar_tabpanel_DatosFom').disable();
						Ext.getCmp('boton_guardar_Aporte').disable();
						Ext.getCmp('boton_guardar_condiciones').disable();
						Ext.getCmp('boton_guardar_Anticipo').disable();
						Ext.getCmp('boton_guardar_modificar').disable();
						Ext.getCmp('boton_guardar_fianzas').disable();
						Ext.getCmp('boton_guardar_paralizaciones').disable();
						Ext.getCmp('boton_guardar_variaciones').disable();
						Ext.getCmp('boton_guardar_valuacion').disable();
						Ext.getCmp('boton_guardar_tramite').disable();
						Ext.getCmp('boton_guardar_cierre').disable();
						Ext.getCmp('boton_eliminar_nuevo_pedido').disable();
						Ext.getCmp('boton_eliminar_nuevo_Aporte').disable();
						Ext.getCmp('boton_eliminar_nuevo_condiciones').disable();
						Ext.getCmp('boton_eliminar_nuevo_Anticipo').disable();
						Ext.getCmp('boton_eliminar_nuevo_valuacion').disable();
						Ext.getCmp('boton_eliminar_nuevo_cierre').disable();
						Ext.getCmp('boton_eliminar_contrato').disable();
						Ext.getCmp('boton_eliminar_tramite').disable();
						Ext.getCmp('usuario').disable();
						//Ext.getCmp('boton_cerrar_tabpanel').enable();
						store_planificacion.load();
					break;
					case '6'://Analista de Contratacion
						Ext.getCmp('menu_planificacion').disable();
						Ext.getCmp('menu_contratacion').enable();
						Ext.getCmp('menu_administracion_contratos').disable();
						//Ext.getCmp('menu_usuarios').disable();
						Ext.getCmp('menu_graficas').enable();
						Ext.getCmp('menu_usuarios').disable();
						Ext.getCmp('menu_administracion').disable();
						//contratacion
						Ext.getCmp('usuario_supervisor').disable();
						Ext.getCmp('usuario_analista').disable();
						Ext.getCmp('boton_exportar_excel_contratacion').enable();
						Ext.getCmp('boton_guardar_datos_generales').enable();
						Ext.getCmp('boton_guardar_datos_procesos').enable();
						Ext.getCmp('boton_guardar_empresa').enable();
						Ext.getCmp('boton_guardar_unidades').enable();
						Ext.getCmp('boton_guardar_panel_cronograma').enable();
						Ext.getCmp('boton_guardar_resultados_rif').enable();
						Ext.getCmp('boton_cerrar_datos_generales').enable();
						Ext.getCmp('boton_cerrar_datos_procesos').enable();
						Ext.getCmp('boton_cerrar_panel_cronograma').enable();
						Ext.getCmp('boton_nuevo_unidades').enable();
						Ext.getCmp('boton_nuevo_resultado_rif').enable();
						Ext.getCmp('boton_eliminar_unidades').enable();
						Ext.getCmp('boton_eliminar_resultados_rif').enable();
						Ext.getCmp('boton_nueva_rif').enable();
						//administracion
						Ext.getCmp('boton_nuevo_contrato').disable();
						Ext.getCmp('boton_nuevo_tramites').disable();
						Ext.getCmp('boton_nuevo_pedido').disable();
						Ext.getCmp('boton_nuevo_Aporte').disable();
						Ext.getCmp('boton_nuevo_condiciones').disable();
						Ext.getCmp('boton_nuevo_Anticipo').disable();
						Ext.getCmp('boton_nuevo_valuacion').disable();
						Ext.getCmp('boton_nueva_modificacion').disable();
						Ext.getCmp('boton_nuevo_Cierre').disable();
						Ext.getCmp('boton_guardar_pedido').disable();
						Ext.getCmp('boton_guardar_asignar').disable();
						Ext.getCmp('boton_guardar_tabpanel_DatosFom').disable();
						Ext.getCmp('boton_guardar_Aporte').disable();
						Ext.getCmp('boton_guardar_condiciones').disable();
						Ext.getCmp('boton_guardar_Anticipo').disable();
						Ext.getCmp('boton_guardar_modificar').disable();
						Ext.getCmp('boton_guardar_fianzas').disable();
						Ext.getCmp('boton_guardar_paralizaciones').disable();
						Ext.getCmp('boton_guardar_variaciones').disable();
						Ext.getCmp('boton_guardar_valuacion').disable();
						Ext.getCmp('boton_guardar_tramite').disable();
						Ext.getCmp('boton_guardar_cierre').disable();
						Ext.getCmp('boton_eliminar_nuevo_pedido').disable();
						Ext.getCmp('boton_eliminar_nuevo_Aporte').disable();
						Ext.getCmp('boton_eliminar_nuevo_condiciones').disable();
						Ext.getCmp('boton_eliminar_nuevo_Anticipo').disable();
						Ext.getCmp('boton_eliminar_nuevo_valuacion').disable();
						Ext.getCmp('boton_eliminar_nuevo_cierre').disable();
						Ext.getCmp('boton_eliminar_contrato').disable();
						Ext.getCmp('boton_eliminar_tramite').disable();
						Ext.getCmp('usuario').disable();
						//Ext.getCmp('boton_cerrar_tabpanel').enable();
						store_planificacion.load();
					break;
					case '7'://Lider de Administracion
						Ext.getCmp('menu_planificacion').disable();
						Ext.getCmp('menu_contratacion').enable();
						Ext.getCmp('menu_administracion_contratos').enable();
						//Ext.getCmp('menu_usuarios').disable();
						Ext.getCmp('menu_graficas').enable();
						Ext.getCmp('menu_usuarios').disable();
						Ext.getCmp('menu_administracion').disable();
						//contratacion
						Ext.getCmp('boton_exportar_excel_contratacion').disable();
						Ext.getCmp('boton_guardar_datos_generales').disable();
						Ext.getCmp('boton_guardar_datos_procesos').disable();
						Ext.getCmp('boton_guardar_empresa').disable();
						Ext.getCmp('boton_guardar_unidades').disable();
						Ext.getCmp('boton_guardar_panel_cronograma').disable();
						Ext.getCmp('boton_guardar_resultados_rif').disable();
						Ext.getCmp('boton_cerrar_datos_generales').disable();
						Ext.getCmp('boton_cerrar_datos_procesos').disable();
						Ext.getCmp('boton_cerrar_panel_cronograma').disable();
						Ext.getCmp('boton_nuevo_unidades').disable();
						Ext.getCmp('boton_nuevo_resultado_rif').disable();
						Ext.getCmp('boton_eliminar_unidades').disable();
						Ext.getCmp('boton_eliminar_resultados_rif').disable();
						Ext.getCmp('boton_nueva_rif').disable();
						//administracion
						Ext.getCmp('boton_nuevo_contrato').disable();
						Ext.getCmp('boton_nuevo_tramites').disable();
						Ext.getCmp('boton_nuevo_pedido').disable();
						Ext.getCmp('boton_nuevo_Aporte').disable();
						Ext.getCmp('boton_nuevo_condiciones').disable();
						Ext.getCmp('boton_nuevo_Anticipo').disable();
						Ext.getCmp('boton_nuevo_valuacion').disable();
						Ext.getCmp('boton_nueva_modificacion').disable();
						Ext.getCmp('boton_nuevo_Cierre').disable();
						Ext.getCmp('boton_guardar_pedido').disable();
						Ext.getCmp('boton_guardar_asignar').enable();
						Ext.getCmp('boton_guardar_tabpanel_DatosFom').disable();
						Ext.getCmp('boton_guardar_Aporte').disable();
						Ext.getCmp('boton_guardar_condiciones').disable();
						Ext.getCmp('boton_guardar_Anticipo').disable();
						Ext.getCmp('boton_guardar_modificar').disable();
						Ext.getCmp('boton_guardar_fianzas').disable();
						Ext.getCmp('boton_guardar_paralizaciones').disable();
						Ext.getCmp('boton_guardar_variaciones').disable();
						Ext.getCmp('boton_guardar_valuacion').disable();
						Ext.getCmp('boton_guardar_tramite').disable();
						Ext.getCmp('boton_guardar_cierre').disable();
						Ext.getCmp('boton_eliminar_nuevo_pedido').disable();
						Ext.getCmp('boton_eliminar_nuevo_Aporte').disable();
						Ext.getCmp('boton_eliminar_nuevo_condiciones').disable();
						Ext.getCmp('boton_eliminar_nuevo_Anticipo').disable();
						Ext.getCmp('boton_eliminar_nuevo_valuacion').disable();
						Ext.getCmp('boton_eliminar_nuevo_cierre').disable();
						Ext.getCmp('boton_eliminar_contrato').disable();
						Ext.getCmp('boton_eliminar_tramite').disable();
						Ext.getCmp('usuario').enable();
						//Ext.getCmp('boton_cerrar_tabpanel').enable();
						store_planificacion.load();
					break;
					case '8'://Supervisor de Administracion
						Ext.getCmp('menu_planificacion').disable();
						Ext.getCmp('menu_contratacion').enable();
						Ext.getCmp('menu_administracion_contratos').enable();
						//Ext.getCmp('menu_usuarios').disable();
						Ext.getCmp('menu_graficas').enable();
						Ext.getCmp('menu_usuarios').disable();
						Ext.getCmp('menu_administracion').disable();
						//contratacion
						Ext.getCmp('boton_exportar_excel_contratacion').disable();
						Ext.getCmp('boton_guardar_datos_generales').disable();
						Ext.getCmp('boton_guardar_datos_procesos').disable();
						Ext.getCmp('boton_guardar_empresa').disable();
						Ext.getCmp('boton_guardar_unidades').disable();
						Ext.getCmp('boton_guardar_panel_cronograma').disable();
						Ext.getCmp('boton_guardar_resultados_rif').disable();
						Ext.getCmp('boton_cerrar_datos_generales').disable();
						Ext.getCmp('boton_cerrar_datos_procesos').disable();
						Ext.getCmp('boton_cerrar_panel_cronograma').disable();
						Ext.getCmp('boton_nuevo_unidades').disable();
						Ext.getCmp('boton_nuevo_resultado_rif').disable();
						Ext.getCmp('boton_eliminar_unidades').disable();
						Ext.getCmp('boton_eliminar_resultados_rif').disable();
						Ext.getCmp('boton_nueva_rif').disable();
						//administracion
						Ext.getCmp('boton_nuevo_contrato').disable();
						Ext.getCmp('boton_nuevo_tramites').disable();
						Ext.getCmp('boton_nuevo_pedido').disable();
						Ext.getCmp('boton_nuevo_Aporte').disable();
						Ext.getCmp('boton_nuevo_condiciones').disable();
						Ext.getCmp('boton_nuevo_Anticipo').disable();
						Ext.getCmp('boton_nuevo_valuacion').disable();
						Ext.getCmp('boton_nueva_modificacion').disable();
						Ext.getCmp('boton_nuevo_Cierre').disable();
						Ext.getCmp('boton_guardar_pedido').disable();
						Ext.getCmp('boton_guardar_asignar').enable();
						Ext.getCmp('boton_guardar_tabpanel_DatosFom').disable();
						Ext.getCmp('boton_guardar_Aporte').disable();
						Ext.getCmp('boton_guardar_condiciones').disable();
						Ext.getCmp('boton_guardar_Anticipo').disable();
						Ext.getCmp('boton_guardar_modificar').disable();
						Ext.getCmp('boton_guardar_fianzas').disable();
						Ext.getCmp('boton_guardar_paralizaciones').disable();
						Ext.getCmp('boton_guardar_variaciones').disable();
						Ext.getCmp('boton_guardar_valuacion').disable();
						Ext.getCmp('boton_guardar_tramite').disable();
						Ext.getCmp('boton_guardar_cierre').disable();
						Ext.getCmp('boton_eliminar_nuevo_pedido').disable();
						Ext.getCmp('boton_eliminar_nuevo_Aporte').disable();
						Ext.getCmp('boton_eliminar_nuevo_condiciones').disable();
						Ext.getCmp('boton_eliminar_nuevo_Anticipo').disable();
						Ext.getCmp('boton_eliminar_nuevo_valuacion').disable();
						Ext.getCmp('boton_eliminar_nuevo_cierre').disable();
						Ext.getCmp('boton_eliminar_contrato').disable();
						Ext.getCmp('boton_eliminar_tramite').disable();
						Ext.getCmp('usuario').enable();
						//Ext.getCmp('boton_cerrar_tabpanel').enable();
						store_planificacion.load();
					break;
					case '9'://Analista de Administracion
						Ext.getCmp('menu_planificacion').disable();
						Ext.getCmp('menu_contratacion').disable();
						Ext.getCmp('menu_administracion_contratos').enable();
						//Ext.getCmp('menu_usuarios').disable();
						Ext.getCmp('menu_graficas').disable();
						Ext.getCmp('menu_usuarios').disable();
						Ext.getCmp('menu_administracion').disable();
						//contratacion
						Ext.getCmp('boton_exportar_excel_contratacion').disable();
						Ext.getCmp('boton_guardar_datos_generales').disable();
						Ext.getCmp('boton_guardar_datos_procesos').disable();
						Ext.getCmp('boton_guardar_empresa').disable();
						Ext.getCmp('boton_guardar_unidades').disable();
						Ext.getCmp('boton_guardar_panel_cronograma').disable();
						Ext.getCmp('boton_guardar_resultados_rif').disable();
						Ext.getCmp('boton_cerrar_datos_generales').disable();
						Ext.getCmp('boton_cerrar_datos_procesos').disable();
						Ext.getCmp('boton_cerrar_panel_cronograma').disable();
						Ext.getCmp('boton_nuevo_unidades').disable();
						Ext.getCmp('boton_nuevo_resultado_rif').disable();
						Ext.getCmp('boton_eliminar_unidades').disable();
						Ext.getCmp('boton_eliminar_resultados_rif').disable();
						Ext.getCmp('boton_nueva_rif').disable();
						//administracion
						Ext.getCmp('boton_nuevo_contrato').enable();
						Ext.getCmp('boton_nuevo_tramites').enable();
						Ext.getCmp('boton_nuevo_pedido').enable();
						Ext.getCmp('boton_nuevo_Aporte').enable();
						Ext.getCmp('boton_nuevo_condiciones').enable();
						Ext.getCmp('boton_nuevo_Anticipo').enable();
						Ext.getCmp('boton_nuevo_valuacion').enable();
						Ext.getCmp('boton_nueva_modificacion').enable();
						Ext.getCmp('boton_nuevo_Cierre').enable();
						Ext.getCmp('boton_guardar_pedido').enable();
						Ext.getCmp('boton_guardar_asignar').disable();
						Ext.getCmp('boton_guardar_tabpanel_DatosFom').enable();
						Ext.getCmp('boton_guardar_Aporte').enable();
						Ext.getCmp('boton_guardar_condiciones').enable();
						Ext.getCmp('boton_guardar_Anticipo').enable();
						Ext.getCmp('boton_guardar_modificar').enable();
						Ext.getCmp('boton_guardar_fianzas').enable();
						Ext.getCmp('boton_guardar_paralizaciones').enable();
						Ext.getCmp('boton_guardar_variaciones').enable();
						Ext.getCmp('boton_guardar_valuacion').enable();
						Ext.getCmp('boton_guardar_tramite').enable();
						Ext.getCmp('boton_guardar_cierre').enable();
						Ext.getCmp('boton_eliminar_nuevo_pedido').enable();
						Ext.getCmp('boton_eliminar_nuevo_Aporte').enable();
						Ext.getCmp('boton_eliminar_nuevo_condiciones').enable();
						Ext.getCmp('boton_eliminar_nuevo_Anticipo').enable();
						Ext.getCmp('boton_eliminar_nuevo_valuacion').enable();
						Ext.getCmp('boton_eliminar_nuevo_cierre').enable();
						Ext.getCmp('boton_eliminar_contrato').disable();
						Ext.getCmp('boton_eliminar_tramite').enable();
						Ext.getCmp('usuario').disable();
						
						//Ext.getCmp('boton_cerrar_tabpanel').enable();
						store_planificacion.load();
					break;
					
					case '10'://Analista de Planificacion
						Ext.getCmp('menu_planificacion').enable();
						Ext.getCmp('menu_contratacion').enable();
						Ext.getCmp('menu_administracion_contratos').disable();
						//Ext.getCmp('menu_usuarios').disable();
						Ext.getCmp('menu_graficas').enable();
						Ext.getCmp('menu_usuarios').disable();
						Ext.getCmp('menu_administracion').disable();
						//planificacion
						Ext.getCmp('boton-guardar-planificacion').enable();
						Ext.getCmp('boton-guardar-planificacion2').enable();
						Ext.getCmp('boton_guardar_solicitud').enable();
						Ext.getCmp('boton-cerrar-planificacion').enable();
						Ext.getCmp('boton_cerrar_procesos').enable();
						Ext.getCmp('boton_cancelar_solicitud').enable();
						Ext.getCmp('boton-nuevo-proceso').enable();
						Ext.getCmp('boton-eliminar-proceso').enable();
						Ext.getCmp('boton-exportar-excel-proceso').enable();
						Ext.getCmp('boton-imprimir-proceso').enable();
						//contratacion
						Ext.getCmp('boton_exportar_excel_contratacion').disable();
						Ext.getCmp('boton_guardar_datos_generales').disable();
						Ext.getCmp('boton_guardar_datos_procesos').disable();
						Ext.getCmp('boton_guardar_empresa').disable();
						Ext.getCmp('boton_guardar_unidades').disable();
						Ext.getCmp('boton_guardar_panel_cronograma').disable();
						Ext.getCmp('boton_guardar_resultados_rif').disable();
						Ext.getCmp('boton_cerrar_datos_generales').disable();
						Ext.getCmp('boton_cerrar_datos_procesos').disable();
						Ext.getCmp('boton_cerrar_panel_cronograma').disable();
						Ext.getCmp('boton_nuevo_unidades').disable();
						Ext.getCmp('boton_nuevo_resultado_rif').disable();
						Ext.getCmp('boton_eliminar_unidades').disable();
						Ext.getCmp('boton_eliminar_resultados_rif').disable();
						Ext.getCmp('boton_nueva_rif').disable();
						//administracion
						Ext.getCmp('boton_nuevo_contrato').disable();
						Ext.getCmp('boton_nuevo_tramites').disable();
						Ext.getCmp('boton_nuevo_pedido').disable();
						Ext.getCmp('boton_nuevo_Aporte').disable();
						Ext.getCmp('boton_nuevo_condiciones').disable();
						Ext.getCmp('boton_nuevo_Anticipo').disable();
						Ext.getCmp('boton_nuevo_valuacion').disable();
						Ext.getCmp('boton_nueva_modificacion').disable();
						Ext.getCmp('boton_nuevo_Cierre').disable();
						Ext.getCmp('boton_guardar_pedido').disable();
						Ext.getCmp('boton_guardar_asignar').disable();
						Ext.getCmp('boton_guardar_tabpanel_DatosFom').disable();
						Ext.getCmp('boton_guardar_Aporte').disable();
						Ext.getCmp('boton_guardar_condiciones').disable();
						Ext.getCmp('boton_guardar_Anticipo').disable();
						Ext.getCmp('boton_guardar_modificar').disable();
						Ext.getCmp('boton_guardar_fianzas').disable();
						Ext.getCmp('boton_guardar_paralizaciones').disable();
						Ext.getCmp('boton_guardar_variaciones').disable();
						Ext.getCmp('boton_guardar_tramite').disable();
						Ext.getCmp('boton_guardar_cierre').disable();
						Ext.getCmp('boton_eliminar_nuevo_pedido').disable();
						Ext.getCmp('boton_eliminar_nuevo_Aporte').disable();
						Ext.getCmp('boton_eliminar_nuevo_condiciones').disable();
						Ext.getCmp('boton_eliminar_nuevo_Anticipo').disable();
						Ext.getCmp('boton_eliminar_nuevo_cierre').disable();
						Ext.getCmp('boton_eliminar_contrato').disable();
						Ext.getCmp('boton_eliminar_tramite').disable();
						Ext.getCmp('usuario').disable();
						//Ext.getCmp('boton_cerrar_tabpanel').enable();
						store_planificacion.load();
					break;
									
					case '12':
						Ext.getCmp('menu_planificacion').enable();
						Ext.getCmp('menu_contratacion').enable();//para que el usuario no pueda ver
						Ext.getCmp('menu_administracion_contratos').disable();
						//Ext.getCmp('menu_usuarios').disable();
						Ext.getCmp('usuario_analista').enable();
						Ext.getCmp('menu_graficas').enable();
						Ext.getCmp('menu_usuarios').enable();
						Ext.getCmp('menu_administracion').enable();
						//planificacion
						Ext.getCmp('boton-guardar-planificacion').enable();
						Ext.getCmp('boton-guardar-planificacion2').enable();
						Ext.getCmp('boton_guardar_solicitud').enable();
						Ext.getCmp('boton-cerrar-planificacion').enable();
						Ext.getCmp('boton_cerrar_procesos').enable();
						Ext.getCmp('boton_cancelar_solicitud').enable();
						Ext.getCmp('boton-nuevo-proceso').enable();
						Ext.getCmp('boton-eliminar-proceso').enable();
						Ext.getCmp('boton-exportar-excel-proceso').enable();
						Ext.getCmp('boton-imprimir-proceso').enable();
						//contratacion
						Ext.getCmp('boton_exportar_excel_contratacion').disable();
						Ext.getCmp('boton_guardar_datos_generales').disable();
						Ext.getCmp('boton_guardar_datos_procesos').disable();
						Ext.getCmp('boton_guardar_empresa').disable();
						Ext.getCmp('boton_guardar_unidades').disable();
						Ext.getCmp('boton_guardar_panel_cronograma').disable();
						Ext.getCmp('boton_guardar_resultados_rif').disable();
						Ext.getCmp('boton_cerrar_datos_generales').disable();
						Ext.getCmp('boton_cerrar_datos_procesos').disable();
						Ext.getCmp('boton_cerrar_panel_cronograma').disable();
						Ext.getCmp('boton_nuevo_unidades').disable();
						Ext.getCmp('boton_nuevo_resultado_rif').disable();
						Ext.getCmp('boton_eliminar_unidades').disable();
						Ext.getCmp('boton_eliminar_resultados_rif').disable();
						Ext.getCmp('boton_nueva_rif').disable();
						//administracion
						Ext.getCmp('boton_nuevo_contrato').disable();
						Ext.getCmp('boton_nuevo_tramites').disable();
						Ext.getCmp('boton_nuevo_pedido').disable();
						Ext.getCmp('boton_nuevo_Aporte').disable();
						Ext.getCmp('boton_nuevo_condiciones').disable();
						Ext.getCmp('boton_nuevo_Anticipo').disable();
						Ext.getCmp('boton_nuevo_valuacion').disable();
						Ext.getCmp('boton_nueva_modificacion').disable();
						Ext.getCmp('boton_nuevo_Cierre').disable();
						Ext.getCmp('boton_guardar_pedido').disable();
						Ext.getCmp('boton_guardar_asignar').disable();
						Ext.getCmp('boton_guardar_tabpanel_DatosFom').disable();
						Ext.getCmp('boton_guardar_Aporte').disable();
						Ext.getCmp('boton_guardar_condiciones').disable();
						Ext.getCmp('boton_guardar_Anticipo').disable();
						Ext.getCmp('boton_guardar_modificar').disable();
						Ext.getCmp('boton_guardar_fianzas').disable();
						Ext.getCmp('boton_guardar_paralizaciones').disable();
						Ext.getCmp('boton_guardar_variaciones').disable();
						Ext.getCmp('boton_guardar_valuacion').disable();
						Ext.getCmp('boton_guardar_tramite').disable();
						Ext.getCmp('boton_guardar_cierre').disable();
						Ext.getCmp('boton_eliminar_nuevo_pedido').disable();
						Ext.getCmp('boton_eliminar_nuevo_Aporte').disable();
						Ext.getCmp('boton_eliminar_nuevo_condiciones').disable();
						Ext.getCmp('boton_eliminar_nuevo_Anticipo').disable();
						Ext.getCmp('boton_eliminar_nuevo_valuacion').disable();
						Ext.getCmp('boton_eliminar_nuevo_cierre').disable();
						Ext.getCmp('boton_eliminar_contrato').disable();
						Ext.getCmp('boton_eliminar_tramite').disable();
						Ext.getCmp('usuario').disable();
						//Ext.getCmp('boton_cerrar_tabpanel').enable();
						store_planificacion.load();
                                                store_usuarios.load();
					break;
				}
				WinLogin.hide();
				//WinLogin.hide();
/*		store_agenda.load({params:{"tx_indicador":Ext.getCmp('tx_usuario').getValue()}});
		store_proceso.load({params:{"tx_indicador":Ext.getCmp('tx_usuario').getValue()}});
		comboComision.store.setBaseParam('tx_indicador',Ext.getCmp('tx_usuario').getValue());
*/
			} 
			else{
				WinError(obj.errors.reason);
				//WinLogin.show();
			}
		},
		failure: function(form, action){						
		},
		
	});	
}
var logo = new Ext.BoxComponent({
    autoEl: {
        tag: 'img',
        //layout:'fit',
                src: 'images/logo_contratos.png',
        
    },
    style:{
           textAlign: 'center'  
       }
/*,
    style: {
            background: '#bacce4'
        }*/
});
var WinLogin = new Ext.Window({
	title: '[CONTRATOS] | PDVSA',
	id:'WinLogin',
	width: 345,
	height: 260,
	resizable:false,
	closeAction: 'hide',
	//bodyStyle:'padding:0px 0px 0px 0px; background-color:#FF0000;',
	plain: true,
	closable:false,
	draggable:false,
	layout:'absolute',
	keys:{
		key:[13],
		fn:function(){ 
			verificarUsuario();			
		},  
		scope:this
    },	
	items: [logo,
	{
		xtype:'label',x:60,y:85,
		html:'<b>Indicador:</b>'
	},{
		xtype:'label',x:60,y:125,
		html:'<b>Contrase&ntilde;a:</b>'
	},{
		xtype:'label',x:60,y:165,
		html:'<b>Rol:</b>'
	},{
		id:'tx_usuario',name:'tx_usuario',
		value:'',
		xtype:'textfield',x:140,y:80,
		listeners: {
			'change': function (field){
				if(Ext.getCmp("tx_usuario").getValue()!=''){
					Ext.getCmp("co_rol").store.reload({params:{"tx_indicador":Ext.getCmp('tx_usuario').getValue()}});
				}					
			}
		}
	},{
		id:'tx_password',
		xtype:'textfield',x:140,y:120,
		value:'',
		inputType:'Password'
	},
	GetComboXY('co_rol','co_rol','roles_usuario',true,140,160)],
	modal:true,
	iconCls: 'login',
	buttonAlign: 'center',
	buttons: [{
		id:'buttonIngresar',
		text: 'Ingresar',
		disabled:false,
		handler: function(){
			verificarUsuario();	
			//WinLogin.hide();
		}
	},
	{
		text: 'Borrar',
		handler: function(){ 
			Ext.getCmp('tx_usuario').setValue('');
			Ext.getCmp('tx_password').setValue('');
			//window.location ="http://intranet.pdvsa.com";
		}
	}]
});

Ext.getCmp("co_rol").store.on('beforeload',function (store,o){		
	Ext.getCmp("buttonIngresar").disable();
	Ext.getCmp("co_rol").disable();
	Ext.getCmp("co_rol").store.removeAll();
	Ext.getCmp("co_rol").reset();
});

Ext.getCmp("co_rol").store.on('datachanged',function (field,newValue,oldValue){		
	if(Ext.getCmp("co_rol").store.getCount()!=0){
		Ext.getCmp("co_rol").setValue(Ext.getCmp("co_rol").store.getAt(0).get('co_rol'));
		Ext.getCmp("co_rol").enable();
		Ext.getCmp("buttonIngresar").enable();
	}
});
